version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: info-log-db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: passwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
